
import { TranslationStrings } from './types';

export const TRANSLATIONS: Record<'ar' | 'en', TranslationStrings> = {
  ar: {
    title: 'تحليل بلس',
    subtitle: 'حلل أي منتج، رابط، أو متجر في السوق السعودي بدقة احترافية',
    searchPlaceholder: 'أدخل اسم المنتج، رابط المنتج، أو رابط المتجر (مثال: سلة، زد، نون...)',
    searchBtn: 'تحليل البيانات العميقة',
    analyzing: 'جاري إجراء مسح شامل للسوق السعودي والتحليل المباشر...',
    resultsTitle: 'تقرير التحليل الاستراتيجي الشامل',
    marketStats: 'إحصائيات السوق الرقمية',
    competitorTable: 'خريطة المنافسين المباشرين',
    swotAnalysis: 'تحليل الرباعي الاستراتيجي (SWOT)',
    recommendations: 'خطة العمل المقترحة',
    priceTrend: 'ديناميكيات الأسعار والطلب',
    store: 'المتجر',
    price: 'السعر (ر.س)',
    rating: 'التقييم',
    shipping: 'الشحن (أيام)',
    status: 'الحالة',
    avgPrice: 'متوسط السعر',
    demand: 'مستوى الطلب',
    saturation: 'تشبع السوق',
    liveBadge: 'تحليل حي ومحدث لسوق المملكة 2025',
    sourcesTitle: 'المصادر والبيانات المرجعية',
    verdictTitle: 'التوصية النهائية لدخول السوق',
    marketDeepDive: 'تحليل الجدوى والاحتياج',
    marketingSection: 'استراتيجية التسويق والجمهور',
    opsSection: 'اللوجستيات والمالية المتوقعة',
    strategySection: 'التميز التنافسي والمخاطر',
  },
  en: {
    title: 'Tahleel Plus',
    subtitle: 'Deep Strategic Analysis for the Saudi E-commerce Market',
    searchPlaceholder: 'Enter product name, link, or store (Salla, Zid, Noon, etc.)',
    searchBtn: 'Deep Data Analysis',
    analyzing: 'Conducting comprehensive Saudi market scan and live analysis...',
    resultsTitle: 'Comprehensive Strategic Analysis Report',
    marketStats: 'Digital Market Statistics',
    competitorTable: 'Direct Competitor Map',
    swotAnalysis: 'Strategic SWOT Analysis',
    recommendations: 'Proposed Action Plan',
    priceTrend: 'Price & Demand Dynamics',
    store: 'Store',
    price: 'Price (SAR)',
    rating: 'Rating',
    shipping: 'Shipping (Days)',
    status: 'Status',
    avgPrice: 'Avg Price',
    demand: 'Demand Level',
    saturation: 'Market Saturation',
    liveBadge: 'Live KSA Market Analysis 2025',
    sourcesTitle: 'Verified Reference Data',
    verdictTitle: 'Final Market Entry Recommendation',
    marketDeepDive: 'Feasibility & Demand Analysis',
    marketingSection: 'Marketing & Audience Strategy',
    opsSection: 'Logistics & Expected Financials',
    strategySection: 'Competitive Edge & Risks',
  },
};
