
import { TranslationStrings } from './types';

export const TRANSLATIONS: Record<'ar' | 'en', TranslationStrings> = {
  ar: {
    title: 'تحليل بلس',
    subtitle: 'حلل أي منتج، رابط، أو متجر بدقة احترافية',
    searchPlaceholder: 'ابحث باسم المنتج أو الرابط...',
    searchBtn: 'تحليل البيانات العميقة',
    analyzing: 'جاري إجراء مسح شامل للسوق والتحليل المباشر...',
    resultsTitle: 'تقرير التحليل الاستراتيجي الشامل',
    marketStats: 'إحصائيات السوق الرقمية',
    competitorTable: 'خريطة المنافسين المباشرين',
    swotAnalysis: 'تحليل الرباعي الاستراتيجي (SWOT)',
    recommendations: 'خطة العمل المقترحة',
    priceTrend: 'ديناميكيات الأسعار والطلب',
    store: 'المتجر',
    price: 'السعر (ر.س)',
    rating: 'التقييم',
    shipping: 'الشحن (أيام)',
    status: 'الحالة',
    avgPrice: 'متوسط السعر',
    demand: 'مستوى الطلب',
    saturation: 'تشبع السوق',
    liveBadge: 'تحليل حي ومحدث للسوق 2025 • بيانات دقيقة من محرك البحث',
    sourcesTitle: 'المصادر والبيانات المرجعية',
    verdictTitle: 'التوصية النهائية لدخول السوق',
    marketDeepDive: 'تحليل الجدوى والاحتياج',
    marketingSection: 'استراتيجية التسويق والجمهور',
    opsSection: 'اللوجستيات والمالية المتوقعة',
    strategySection: 'التميز التنافسي والمخاطر',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    signup: 'إنشاء حساب جديد',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    alreadyHaveAccount: 'لديك حساب بالفعل؟ سجل دخولك',
    dontHaveAccount: 'ليس لديك حساب؟ اشترك الآن',
    adminBadge: 'لوحة التحكم - المشرف',
    welcome: 'مرحباً بك في تحليل بلس',
    authRequired: 'يرجى تسجيل الدخول للوصول إلى محرك البحث المتقدم',
    pricingTitle: 'خطط الاشتراك',
    pricingSubtitle: 'اختر الباقة المناسبة لاحتياجاتك التجارية',
    subscribeNow: 'اشترك الآن',
    manageUsers: 'إدارة المستخدمين والاشتراكات',
    userEmail: 'البريد الإلكتروني',
    userPlan: 'الباقة الحالية',
    userStatus: 'حالة الحساب',
    actions: 'إجراءات',
    noAccess: 'عذراً، يجب ترقية باقتك للوصول لهذا التحليل العميق.',
    forgotPassword: 'نسيت كلمة المرور؟',
    resetSent: 'تم إرسال رابط استعادة كلمة المرور إلى بريدك الإلكتروني.',
    emailInUse: 'هذا البريد الإلكتروني مسجل مسبقاً. يرجى تسجيل الدخول بدلاً من الاشتراك.',
    wrongPassword: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
    getKey: 'احصل على المفتاح',
    profile: 'الملف الشخصي',
    updateProfile: 'تحديث البيانات',
    displayName: 'الاسم الكامل',
    saveChanges: 'حفظ التعديلات',
    changePassword: 'تغيير كلمة المرور',
    newPassword: 'كلمة المرور الجديدة',
    deleteAccount: 'حذف الحساب نهائياً',
    deleteAccountWarning: '⚠️ تحذير: سيتم حذف كافة بياناتك وتقاريرك نهائياً. لا يمكن التراجع عن هذا الإجراء.',
    reauthRequired: 'يتطلب هذا الإجراء تسجيل الدخول مرة أخرى للأمان.',
    verdicts: {
      'GO': 'انطلق (فرصة استثمارية واعدة)',
      'NO-GO': 'لا ينصح دخول السوق في هذا المجال (مخاطرة عالية)',
      'PROCEED WITH CAUTION': 'تقدم بحذر (دراسة أعمق مطلوبة)'
    },
    levels: {
      'High': 'مرتفع',
      'Medium': 'متوسط',
      'Low': 'منخفض'
    },
    // Dashboard tabs and sections
    monthlyDemand: 'الطلب الشهري',
    demandScore: 'نقاط الطلب',
    stability: 'الاستقرار',
    peakMonths: 'أشهر الذروة',
    lowMonths: 'أشهر الركود',
    unitsEstimated: 'وحدة متوقعة',
    overallStrength: 'القوة الإجمالية',
    volatilityLevel: 'مستوى التقلب',
    estimatedAtExpectedSales: 'متوقع عند حجم المبيعات المتوقع',
    startupInvestment: 'استثمار البداية',
    easeOfEntry: 'سهولة الدخول',
    demandAnalysis: 'تحليل الطلب',
    marketDemandEvaluation: 'تقييم شامل لطلب السوق',
    activeCompetitors: 'المنافسون النشطون',
    strengthIndex: 'مؤشر القوة',
    entryDifficulty: 'صعوبة الدخول',
    marketGaps: 'فجوات السوق',
    opportunitiesIdentified: 'فرص محددة',
    competitorsTable: 'جدول المنافسين',
    averageSalePrice: 'متوسط سعر البيع',
    profitMargin: 'هامش الربح',
    breakEvenPoint: 'نقطة التعادل',
    profitabilityScore: 'نقاط الربحية',
    monthlyRevenue: 'الإيرادات الشهرية',
    revenueStreams: 'مصادر الإيرادات',
    profitDrivers: 'محركات الربح',
    successScore: 'نقاط النجاح',
    probabilityOfSuccess: 'احتمالية النجاح',
    riskScore: 'نقاط المخاطر',
    beginnerFriendly: 'مناسب للمبتدئين',
    capitalRequired: 'رأس المال المطلوب',
    swotStrengths: 'نقاط القوة',
    swotWeaknesses: 'نقاط الضعف',
    swotOpportunities: 'الفرص',
    swotThreats: 'التهديدات',
    demandTrend: 'اتجاه الطلب',
    seasonalityAnalysis: 'تحليل الموسمية',
    geographicDistribution: 'التوزيع الجغرافي',
    competitorAnalysis: 'تحليل المنافسين',
    competitorIntelligence: 'استخبارات المنافسين والموقع السوقي',
    marketGapsOpportunities: 'الفجوات السوقية والفرص',
    profitabilityAnalysis: 'تحليل الربحية',
    revenueAndProfit: 'تقييم إمكانات الإيرادات ومقاييس الربح',
    priceSensitivity: 'حساسية السعر',
    costStructure: 'هيكل التكاليف',
    days: 'أيام',
    sar: 'ر.س',
    strengthRating: 'تقييم القوة',
    pricingViability: 'جدوى التسعير',
    expectedProfitMargins: 'هوامش الربح المتوقعة',
    supplyChainEase: 'سهولة سلسلة التوريد',
    paymentMethods: 'طرق الدفع',
    deliveryMethods: 'طرق التوصيل',
    decisionMetrics: 'مقاييس القرار',
    strategicDecisionFramework: 'إطار القرار الاستراتيجي للاستثمار',
    timeToProfit: 'الوقت للربح',
    estimatedBreakEven: 'الجدول الزمني المتوقع للتعادل',
    goWithConfidence: 'انطلق - تقدم بثقة',
    cautionConsiderRisks: 'حذر - ضع المخاطر في الاعتبار',
    noGoNotRecommended: 'لا ينصح دخول السوق في هذا المجال',
    basedOnAnalysis: 'هذه التوصية مبنية على تحليل شامل للسوق والمنافسة ومقاييس الربحية',
    growthOpportunities: 'فرص النمو',
    identifiedGaps: 'الفجوات السوقية المحددة واستراتيجيات التوسع',
    noOpportunities: 'لا توجد فرص محددة',
    type: 'النوع',
    uniqueSellingProposition: 'العرض الفريد',
    saturationRisk: 'مخاطر التشبع',
    imitationRisk: 'مخاطر التقليد',
    directCompetitors: 'المنافسون المباشرون',
    // New sections
    buyerIntentAnalysis: 'تحليل نية الشراء',
    buyerIntentDescription: 'تحليل سلوك المشتري ونية الشراء',
    intentScore: 'مؤشر نية الشراء',
    intentLevel: 'مستوى النية',
    searchIntentType: 'نوع نية البحث',
    unlockSearchEngine: 'فتح محرك البحث',
    searchHistoryTitle: 'سجل البحث والتجربة المجانية',
    searchHistoryQuestion: 'هل تريد مراجعة سجل بحثك السابق؟',
    tryFreeTrialDescription: 'لديك 3 عمليات بحث مجانية متاحة. استفد من التجربة المجانية الآن!',
    reviewPreviousSearches: 'مراجعة البحث السابق',
    useFreeSearches: 'استخدام التجارب المجانية',
    noSearchHistory: 'لا يوجد سجل بحث سابق',
    buyerJourneyStage: 'مرحلة رحلة المشتري',
    conversionProbability: 'احتمالية التحويل',
    keywordAnalysis: 'تحليل الكلمات المفتاحية',
    transactionalKeywords: 'كلمات شرائية',
    informationalKeywords: 'كلمات معلوماتية',
    brandKeywords: 'كلمات العلامات التجارية',
    insights: 'رؤى وتوصيات',
    growthScenarios: 'سيناريوهات النمو',
    growthScenariosDescription: 'توقعات النمو والإيرادات المحتملة',
    conservativeScenario: 'سيناريو متحفظ',
    moderateScenario: 'سيناريو متوسط',
    optimisticScenario: 'سيناريو متفائل',
    recommendedScenario: 'السيناريو الموصى به',
    monthlyProfit: 'الربح الشهري',
    growthRate: 'معدل النمو',
    timeframe: 'الإطار الزمني',
    assumptions: 'الافتراضات',
    scalabilityFactors: 'عوامل قابلية التوسع',
    executiveSummary: 'الملخص التنفيذي',
    executiveSummaryDescription: 'ملخص تنفيذي شامل من صفحة واحدة',
    onePageSummary: 'الملخص',
    keyFindings: 'النتائج الرئيسية',
    criticalMetrics: 'المقاييس الحرجة',
    marketSize: 'حجم السوق',
    investmentRequired: 'الاستثمار المطلوب',
    initialInvestment: 'الاستثمار الأولي',
    monthlyInvestment: 'الاستثمار الشهري',
    breakEven: 'التعادل',
    strategicRecommendation: 'التوصية الاستراتيجية',
    nextSteps: 'الخطوات التالية',
    transactional: 'شرائي',
    informational: 'معلوماتي',
    mixed: 'مختلط'
  },
  en: {
    title: 'Tahleel Plus',
    subtitle: 'Deep Strategic Analysis for Global E-commerce Markets',
    searchPlaceholder: 'Search by product name or link...',
    searchBtn: 'Deep Data Analysis',
    analyzing: 'Conducting comprehensive market scan and live analysis...',
    resultsTitle: 'Comprehensive Strategic Analysis Report',
    marketStats: 'Digital Market Statistics',
    competitorTable: 'Direct Competitor Map',
    swotAnalysis: 'Strategic SWOT Analysis',
    recommendations: 'Proposed Action Plan',
    priceTrend: 'Price & Demand Dynamics',
    store: 'Store',
    price: 'Price (SAR)',
    rating: 'Rating',
    shipping: 'Shipping (Days)',
    status: 'Status',
    avgPrice: 'Avg Price',
    demand: 'Demand Level',
    saturation: 'Market Saturation',
    liveBadge: 'Live Market Analysis 2025 • Real-time data from search engine',
    sourcesTitle: 'Verified Reference Data',
    verdictTitle: 'Final Market Entry Recommendation',
    marketDeepDive: 'Feasibility & Demand Analysis',
    marketingSection: 'Marketing & Audience Strategy',
    opsSection: 'Logistics & Expected Financials',
    strategySection: 'Competitive Edge & Risks',
    login: 'Login',
    logout: 'Logout',
    signup: 'Create Account',
    email: 'Email Address',
    password: 'Password',
    alreadyHaveAccount: 'Already have an account? Login',
    dontHaveAccount: "Don't have an account? Sign Up",
    adminBadge: 'Admin Dashboard',
    welcome: 'Welcome to Tahleel Plus',
    authRequired: 'Please login to access the advanced search engine',
    pricingTitle: 'Subscription Plans',
    pricingSubtitle: 'Select the perfect plan for your business growth',
    subscribeNow: 'Subscribe Now',
    manageUsers: 'User & Subscription Management',
    userEmail: 'User Email',
    userPlan: 'Current Plan',
    userStatus: 'Account Status',
    actions: 'Actions',
    noAccess: 'Sorry, you need to upgrade your plan to access deep analysis.',
    forgotPassword: 'Forgot Password?',
    resetSent: 'A password reset link has been sent to your email.',
    emailInUse: 'This email is already in use. Please login instead.',
    wrongPassword: 'Invalid email or password.',
    getKey: 'Get Key',
    profile: 'Profile Settings',
    updateProfile: 'Update Profile',
    displayName: 'Full Name',
    saveChanges: 'Save Changes',
    changePassword: 'Change Password',
    newPassword: 'New Password',
    deleteAccount: 'Delete Account',
    deleteAccountWarning: '⚠️ Warning: All your data and reports will be permanently deleted. This action cannot be undone.',
    reauthRequired: 'This action requires you to re-authenticate for security.',
    verdicts: {
      'GO': 'GO (High Potential)',
      'NO-GO': 'NO-GO (High Risk)',
      'PROCEED WITH CAUTION': 'PROCEED WITH CAUTION'
    },
    levels: {
      'High': 'High',
      'Medium': 'Medium',
      'Low': 'Low'
    },
    // Dashboard tabs and sections
    monthlyDemand: 'Monthly Demand',
    demandScore: 'Demand Score',
    stability: 'Stability',
    peakMonths: 'Peak Months',
    lowMonths: 'Low Months',
    unitsEstimated: 'units estimated',
    overallStrength: 'overall strength',
    volatilityLevel: 'volatility level',
    estimatedAtExpectedSales: 'estimated at expected sales volume',
    startupInvestment: 'startup investment',
    easeOfEntry: 'ease of entry',
    demandAnalysis: 'Demand Analysis',
    marketDemandEvaluation: 'Comprehensive market demand evaluation',
    activeCompetitors: 'Active Competitors',
    strengthIndex: 'Strength Index',
    entryDifficulty: 'Entry Difficulty',
    marketGaps: 'Market Gaps',
    opportunitiesIdentified: 'opportunities identified',
    competitorsTable: 'Competitors Table',
    averageSalePrice: 'Average Sale Price',
    profitMargin: 'Profit Margin',
    breakEvenPoint: 'Break Even Point',
    profitabilityScore: 'Profitability Score',
    monthlyRevenue: 'Monthly Revenue',
    revenueStreams: 'Revenue Streams',
    profitDrivers: 'Profit Drivers',
    successScore: 'Success Score',
    riskScore: 'Risk Score',
    beginnerFriendly: 'Beginner Friendly',
    capitalRequired: 'Capital Required',
    swotStrengths: 'Strengths',
    swotWeaknesses: 'Weaknesses',
    swotOpportunities: 'Opportunities',
    swotThreats: 'Threats',
    demandTrend: 'Demand Trend',
    seasonalityAnalysis: 'Seasonality Analysis',
    geographicDistribution: 'Geographic Distribution',
    competitorAnalysis: 'Competitor Analysis',
    competitorIntelligence: 'Strategic competitor intelligence and market positioning',
    marketGapsOpportunities: 'Market Gaps & Opportunities',
    profitabilityAnalysis: 'Profitability Analysis',
    revenueAndProfit: 'Revenue potential and profit metrics evaluation',
    priceSensitivity: 'Price Sensitivity',
    costStructure: 'Cost Structure',
    low: 'Low',
    high: 'High',
    days: 'days',
    sar: 'SAR',
    strengthRating: 'strength rating',
    pricingViability: 'Pricing Viability',
    expectedProfitMargins: 'Expected Profit Margins',
    supplyChainEase: 'Supply Chain Ease',
    paymentMethods: 'Payment Methods',
    deliveryMethods: 'Delivery Methods',
    decisionMetrics: 'Decision Metrics',
    strategicDecisionFramework: 'Strategic Investment Decision Framework',
    timeToProfit: 'Time to Profit',
    estimatedBreakEven: 'Estimated Break-Even Timeline',
    goWithConfidence: 'GO - Proceed with Confidence',
    cautionConsiderRisks: 'CAUTION - Consider Risks',
    noGoNotRecommended: 'NO-GO - Not Recommended',
    basedOnAnalysis: 'This recommendation is based on comprehensive market, competition, and profitability analysis',
    growthOpportunities: 'Growth Opportunities',
    identifiedGaps: 'Identified market gaps and expansion strategies',
    noOpportunities: 'No specific opportunities identified',
    type: 'Type',
    uniqueSellingProposition: 'Unique Selling Proposition',
    saturationRisk: 'Saturation Risk',
    imitationRisk: 'Imitation Risk',
    directCompetitors: 'Direct Competitors',
    // New sections
    buyerIntentAnalysis: 'Buyer Intent Analysis',
    buyerIntentDescription: 'Customer behavior and purchase intent analysis',
    intentScore: 'Intent Score',
    intentLevel: 'Intent Level',
    searchIntentType: 'Search Intent Type',
    buyerJourneyStage: 'Buyer Journey Stage',
    conversionProbability: 'Conversion Probability',
    keywordAnalysis: 'Keyword Analysis',
    transactionalKeywords: 'Transactional Keywords',
    informationalKeywords: 'Informational Keywords',
    brandKeywords: 'Brand Keywords',
    insights: 'Insights & Recommendations',
    growthScenarios: 'Growth Scenarios',
    growthScenariosDescription: 'Growth forecasts and revenue potential',
    conservativeScenario: 'Conservative Scenario',
    moderateScenario: 'Moderate Scenario',
    optimisticScenario: 'Optimistic Scenario',
    recommendedScenario: 'Recommended Scenario',
    monthlyProfit: 'Monthly Profit',
    growthRate: 'Growth Rate',
    timeframe: 'Timeframe',
    assumptions: 'Assumptions',
    scalabilityFactors: 'Scalability Factors',
    executiveSummary: 'Executive Summary',
    executiveSummaryDescription: 'Comprehensive one-page executive summary',
    onePageSummary: 'Summary',
    keyFindings: 'Key Findings',
    criticalMetrics: 'Critical Metrics',
    marketSize: 'Market Size',
    investmentRequired: 'Investment Required',
    initialInvestment: 'Initial Investment',
    monthlyInvestment: 'Monthly Investment',
    breakEven: 'Break Even',
    strategicRecommendation: 'Strategic Recommendation',
    nextSteps: 'Next Steps',
    transactional: 'Transactional',
    informational: 'Informational',
    mixed: 'Mixed'
  }
};

export const LOADING_MESSAGES = {
  ar: [
    "استخراج بيانات الأسعار من المنصات...",
    "جمع معلومات التقييمات والمراجعات...",
    "تحليل أرقام المبيعات والطلب...",
    "معالجة بيانات المنافسين...",
    "حساب متوسط الأسعار والهوامش...",
    "استخلاص أنماط الطلب والموسمية...",
    "تقييم قوة المنتج في السوق...",
    "حساب سيناريوهات النمو المحتملة...",
    "تحليل سلوك المستهلك والشراء...",
    "استخراج فرص النمو المتاحة...",
    "تقييم المخاطر والتحديات...",
    "حساب العائد على الاستثمار المتوقع...",
    "صياغة التوصيات النهائية...",
    "تجميع النتائج والبيانات...",
    "إنهاء التحليل الشامل..."
  ],
  en: [
    "Extracting price data from platforms...",
    "Gathering ratings and reviews information...",
    "Analyzing sales figures and demand patterns...",
    "Processing competitor data...",
    "Calculating average prices and margins...",
    "Extracting demand seasonality trends...",
    "Evaluating product market strength...",
    "Computing potential growth scenarios...",
    "Analyzing consumer behavior and purchasing...",
    "Extracting available growth opportunities...",
    "Evaluating risks and challenges...",
    "Calculating expected return on investment...",
    "Formulating final recommendations...",
    "Compiling results and data...",
    "Completing comprehensive analysis..."
  ]
};

export const REGIONS = [
  // دول عربية
  { code: 'SA', nameAr: 'المملكة العربية السعودية', nameEn: 'Saudi Arabia', googleCode: 'SA' },
  { code: 'EG', nameAr: 'مصر', nameEn: 'Egypt', googleCode: 'EG' },
  { code: 'AE', nameAr: 'الإمارات العربية المتحدة', nameEn: 'United Arab Emirates', googleCode: 'AE' },
  { code: 'JO', nameAr: 'الأردن', nameEn: 'Jordan', googleCode: 'JO' },
  { code: 'KW', nameAr: 'الكويت', nameEn: 'Kuwait', googleCode: 'KW' },
  { code: 'QA', nameAr: 'قطر', nameEn: 'Qatar', googleCode: 'QA' },
  { code: 'BH', nameAr: 'البحرين', nameEn: 'Bahrain', googleCode: 'BH' },
  { code: 'OM', nameAr: 'عمان', nameEn: 'Oman', googleCode: 'OM' },
  { code: 'LB', nameAr: 'لبنان', nameEn: 'Lebanon', googleCode: 'LB' },
  { code: 'SY', nameAr: 'سوريا', nameEn: 'Syria', googleCode: 'SY' },
  { code: 'IQ', nameAr: 'العراق', nameEn: 'Iraq', googleCode: 'IQ' },
  { code: 'MA', nameAr: 'المغرب', nameEn: 'Morocco', googleCode: 'MA' },
  { code: 'TN', nameAr: 'تونس', nameEn: 'Tunisia', googleCode: 'TN' },
  { code: 'DZ', nameAr: 'الجزائر', nameEn: 'Algeria', googleCode: 'DZ' },
  
  // دول آسيوية
  { code: 'IN', nameAr: 'الهند', nameEn: 'India', googleCode: 'IN' },
  { code: 'PK', nameAr: 'باكستان', nameEn: 'Pakistan', googleCode: 'PK' },
  { code: 'BD', nameAr: 'بنغلاديش', nameEn: 'Bangladesh', googleCode: 'BD' },
  { code: 'SG', nameAr: 'سنغافورة', nameEn: 'Singapore', googleCode: 'SG' },
  { code: 'MY', nameAr: 'ماليزيا', nameEn: 'Malaysia', googleCode: 'MY' },
  { code: 'TH', nameAr: 'تايلاند', nameEn: 'Thailand', googleCode: 'TH' },
  { code: 'PH', nameAr: 'الفلبين', nameEn: 'Philippines', googleCode: 'PH' },
  { code: 'ID', nameAr: 'إندونيسيا', nameEn: 'Indonesia', googleCode: 'ID' },
  { code: 'VN', nameAr: 'فيتنام', nameEn: 'Vietnam', googleCode: 'VN' },
  
  // دول أوروبية
  { code: 'GB', nameAr: 'المملكة المتحدة', nameEn: 'United Kingdom', googleCode: 'GB' },
  { code: 'DE', nameAr: 'ألمانيا', nameEn: 'Germany', googleCode: 'DE' },
  { code: 'FR', nameAr: 'فرنسا', nameEn: 'France', googleCode: 'FR' },
  { code: 'ES', nameAr: 'إسبانيا', nameEn: 'Spain', googleCode: 'ES' },
  { code: 'IT', nameAr: 'إيطاليا', nameEn: 'Italy', googleCode: 'IT' },
  { code: 'NL', nameAr: 'هولندا', nameEn: 'Netherlands', googleCode: 'NL' },
  { code: 'SE', nameAr: 'السويد', nameEn: 'Sweden', googleCode: 'SE' },
  { code: 'CH', nameAr: 'سويسرا', nameEn: 'Switzerland', googleCode: 'CH' },
  { code: 'AT', nameAr: 'النمسا', nameEn: 'Austria', googleCode: 'AT' },
  { code: 'PL', nameAr: 'بولندا', nameEn: 'Poland', googleCode: 'PL' },
  
  // دول أفريقية
  { code: 'NG', nameAr: 'نيجيريا', nameEn: 'Nigeria', googleCode: 'NG' },
  { code: 'ZA', nameAr: 'جنوب أفريقيا', nameEn: 'South Africa', googleCode: 'ZA' },
  { code: 'KE', nameAr: 'كينيا', nameEn: 'Kenya', googleCode: 'KE' },
  
  // دول أمريكية
  { code: 'US', nameAr: 'الولايات المتحدة', nameEn: 'United States', googleCode: 'US' },
  { code: 'CA', nameAr: 'كندا', nameEn: 'Canada', googleCode: 'CA' },
  { code: 'MX', nameAr: 'المكسيك', nameEn: 'Mexico', googleCode: 'MX' },
  { code: 'BR', nameAr: 'البرازيل', nameEn: 'Brazil', googleCode: 'BR' },
  { code: 'AR', nameAr: 'الأرجنتين', nameEn: 'Argentina', googleCode: 'AR' },
];

export const COUNTRY_INFO: Record<string, {
  currency: string;
  currencyCode: string;
  language: string;
  platforms: string[];
  topStores: string[];
  marketChar: string;
}> = {
  'SA': {
    currency: 'الريال السعودي',
    currencyCode: 'SAR',
    language: 'العربية',
    platforms: ['سلة', 'زد', 'نون', 'أمازون السعودية', 'إكسباند كارت'],
    topStores: ['أمازون السعودية', 'نون', 'جرير', 'إكسترا', 'نمشي', 'شي إن', 'باث اند بودي', 'سيفي', 'العربية للعود', 'الشايع', 'أناس', 'ستايلي', 'VogaCloset', 'ممزورلد', 'أوناس'],
    marketChar: 'سوق شاب ومتنامي مع رؤية 2030 والتحول الرقمي'
  },
  'EG': {
    currency: 'الجنيه المصري',
    currencyCode: 'EGP',
    language: 'العربية',
    platforms: ['جوميا', 'سوق.كوم', 'أمازون مصر', 'أوليكس', 'أسواق'],
    topStores: ['أمازون مصر', 'جوميا', 'نون مصر', 'بي تك', 'رنين', 'كارفور', 'أوليكس'],
    marketChar: 'أكبر سوق عربي بعدد سكان كبير وطلب قوي'
  },
  'AE': {
    currency: 'الدرهم الإماراتي',
    currencyCode: 'AED',
    language: 'العربية',
    platforms: ['نون', 'أمازون الإمارات', 'جوميا', 'أسواق', 'دبي ستور'],
    topStores: ['أمازون الإمارات', 'نون', 'نمشي', 'أوناس', 'كارفور', 'شرف دي جي', 'جامبو'],
    marketChar: 'سوق متطور وعالي الجودة مع طلب على المنتجات الفاخرة'
  },
  'JO': {
    currency: 'الدينار الأردني',
    currencyCode: 'JOD',
    language: 'العربية',
    platforms: ['جوميا', 'أسواق', 'أمازون', 'ريحاني'],
    topStores: ['أمازون', 'جوميا', 'أوبنسوق', 'كارفور', 'ماركا في آي بي'],
    marketChar: 'سوق متوسط الحجم مع نمو تدريجي'
  },
  'KW': {
    currency: 'الدينار الكويتي',
    currencyCode: 'KWD',
    language: 'العربية',
    platforms: ['نون', 'أمازون', 'جوميا', 'كويت سوق'],
    topStores: ['نون الكويت', 'أمازون', 'إكسترا الكويت', 'إكس سايت', 'الشايع'],
    marketChar: 'سوق غني بقدرة شرائية عالية'
  },
  'QA': {
    currency: 'الريال القطري',
    currencyCode: 'QAR',
    language: 'العربية',
    platforms: ['نون', 'أمازون', 'جوميا'],
    topStores: ['نون قطر', 'أمازون', 'كارفور قطر', 'لولو هايبر ماركت'],
    marketChar: 'سوق صغير الحجم مع دخل عالي جداً'
  },
  'BH': {
    currency: 'الدينار البحريني',
    currencyCode: 'BHD',
    language: 'العربية',
    platforms: ['نون', 'أمازون', 'جوميا'],
    topStores: ['نون البحرين', 'أمازون', 'كارفور البحرين'],
    marketChar: 'سوق صغير لكن بقدرة شرائية عالية'
  },
  'OM': {
    currency: 'الريال العماني',
    currencyCode: 'OMR',
    language: 'العربية',
    platforms: ['أمازون', 'جوميا', 'عماني سوق'],
    topStores: ['أمازون عمان', 'لولو هايبر ماركت', 'كارفور عمان'],
    marketChar: 'سوق متنامي مع نمو التجارة الإلكترونية'
  },
  'LB': {
    currency: 'الليرة اللبنانية',
    currencyCode: 'LBP',
    language: 'العربية',
    platforms: ['أمازون', 'جوميا', 'أسواق'],
    topStores: ['أمازون', 'كارفور لبنان'],
    marketChar: 'سوق متوسط مع تحديات اقتصادية'
  },
  'SY': {
    currency: 'الليرة السورية',
    currencyCode: 'SYP',
    language: 'العربية',
    platforms: ['أسواق محلية', 'سوق إلكترونية'],
    topStores: ['أسواق محلية'],
    marketChar: 'سوق محدود بسبب الظروف السياسية'
  },
  'IQ': {
    currency: 'الدينار العراقي',
    currencyCode: 'IQD',
    language: 'العربية',
    platforms: ['سوق إلكترونية', 'أمازون'],
    topStores: ['أمازون', 'كارفور العراق', 'أسواق محلية'],
    marketChar: 'سوق نامٍ مع إمكانيات كبيرة'
  },
  'MA': {
    currency: 'الدرهم المغربي',
    currencyCode: 'MAD',
    language: 'العربية',
    platforms: ['جوميا', 'أمازون', 'أسواق'],
    topStores: ['جوميا المغرب', 'أفيتو', 'مارجان'],
    marketChar: 'سوق قوي بأفريقيا الشمالية'
  },
  'TN': {
    currency: 'الدينار التونسي',
    currencyCode: 'TND',
    language: 'العربية',
    platforms: ['جوميا', 'أمازون', 'أسواق'],
    topStores: ['جوميا تونس', 'مايشوب تونس'],
    marketChar: 'سوق متوسط مع تطور تكنولوجي'
  },
  'DZ': {
    currency: 'الدينار الجزائري',
    currencyCode: 'DZD',
    language: 'العربية',
    platforms: ['جوميا', 'أمازون', 'سوق إلكترونية'],
    topStores: ['جوميا الجزائر', 'أوديكس'],
    marketChar: 'سوق كبير بإمكانيات عالية'
  },
  'IN': {
    currency: 'الروبية الهندية',
    currencyCode: 'INR',
    language: 'الإنجليزية',
    platforms: ['Amazon.in', 'Flipkart', 'Snapdeal', 'Myntra'],
    topStores: ['Amazon India', 'Flipkart', 'Snapdeal', 'Myntra', 'Nykaa', 'Ajio'],
    marketChar: 'أكبر سوق إلكترونية آسيوية بسعر منخفض'
  },
  'PK': {
    currency: 'الروبية الباكستانية',
    currencyCode: 'PKR',
    language: 'الإنجليزية',
    platforms: ['Daraz', 'TCS', 'Telemart', 'Alibaba'],
    topStores: ['Daraz', 'Telemart', 'Goto.pk', 'PakStyle'],
    marketChar: 'سوق متنامي بسرعة مع مشترين شباب'
  },
  'BD': {
    currency: 'الطاكا البنغلاديشية',
    currencyCode: 'BDT',
    language: 'الإنجليزية',
    platforms: ['Daraz', 'Alibaba', 'AjkerDeal'],
    topStores: ['Daraz Bangladesh', 'AjkerDeal', 'Evaly', 'Pickaboo'],
    marketChar: 'سوق نام مع تحسن مستمر'
  },
  'SG': {
    currency: 'الدولار السنغافوري',
    currencyCode: 'SGD',
    language: 'الإنجليزية',
    platforms: ['Lazada', 'Shopee', 'Amazon', 'Carousell'],
    topStores: ['Lazada', 'Shopee', 'Amazon Singapore', 'Qoo10', 'Carousell'],
    marketChar: 'سوق متطور وعالي الجودة'
  },
  'MY': {
    currency: 'الرينجيت الماليزي',
    currencyCode: 'MYR',
    language: 'الإنجليزية',
    platforms: ['Lazada', 'Shopee', 'Amazon', 'Mudah'],
    topStores: ['Lazada Malaysia', 'Shopee Malaysia', 'Zalora', 'Mudah'],
    marketChar: 'سوق متنامي بسرعة في جنوب شرق آسيا'
  },
  'TH': {
    currency: 'البات التايلاندي',
    currencyCode: 'THB',
    language: 'الإنجليزية',
    platforms: ['Lazada', 'Shopee', 'JD.co.th', 'Blibli'],
    topStores: ['Lazada Thailand', 'Shopee Thailand', 'JD Central', 'Central Online'],
    marketChar: 'سوق قوي في جنوب شرق آسيا'
  },
  'PH': {
    currency: 'البيزو الفلبيني',
    currencyCode: 'PHP',
    language: 'الإنجليزية',
    platforms: ['Lazada', 'Shopee', 'Zalora', 'Amazon'],
    topStores: ['Lazada Philippines', 'Shopee Philippines', 'Zalora', 'BeautyMNL'],
    marketChar: 'سوق شاب ومتنامي'
  },
  'ID': {
    currency: 'الروبية الإندونيسية',
    currencyCode: 'IDR',
    language: 'الإنجليزية',
    platforms: ['Tokopedia', 'Shopee', 'Lazada', 'Bukalapak'],
    topStores: ['Tokopedia', 'Shopee Indonesia', 'Lazada Indonesia', 'Bukalapak', 'Blibli'],
    marketChar: 'أكبر سوق في جنوب شرق آسيا'
  },
  'VN': {
    currency: 'الدونج الفيتنامي',
    currencyCode: 'VND',
    language: 'الإنجليزية',
    platforms: ['Shopee', 'Lazada', 'Sendo', 'TikTok Shop'],
    topStores: ['Shopee Vietnam', 'Lazada Vietnam', 'Tiki', 'Sendo'],
    marketChar: 'سوق نام بسرعة كبيرة'
  },
  'GB': {
    currency: 'الجنيه الإسترليني',
    currencyCode: 'GBP',
    language: 'English',
    platforms: ['Amazon UK', 'eBay UK', 'ASOS', 'Etsy'],
    topStores: ['Amazon UK', 'eBay UK', 'ASOS', 'Argos', 'John Lewis', 'Currys'],
    marketChar: 'سوق متطور وناضج'
  },
  'DE': {
    currency: 'اليورو',
    currencyCode: 'EUR',
    language: 'English',
    platforms: ['Amazon.de', 'eBay', 'Kaufland', 'Otto'],
    topStores: ['Amazon Germany', 'eBay Germany', 'Otto', 'Zalando', 'MediaMarkt'],
    marketChar: 'سوق قوي وموثوق'
  },
  'FR': {
    currency: 'اليورو',
    currencyCode: 'EUR',
    language: 'English',
    platforms: ['Amazon.fr', 'eBay', 'Cdiscount', 'Fnac'],
    topStores: ['Amazon France', 'Cdiscount', 'Fnac', 'Veepee', 'La Redoute'],
    marketChar: 'سوق متطور بمعايير عالية'
  },
  'ES': {
    currency: 'اليورو',
    currencyCode: 'EUR',
    language: 'English',
    platforms: ['Amazon.es', 'eBay', 'Mercado', 'Carrefour'],
    topStores: ['Amazon Spain', 'El Corte Inglés', 'PcComponentes', 'Carrefour'],
    marketChar: 'سوق جيد مع منافسة قوية'
  },
  'IT': {
    currency: 'اليورو',
    currencyCode: 'EUR',
    language: 'English',
    platforms: ['Amazon.it', 'eBay', 'Subito', 'Unieuro'],
    topStores: ['Amazon Italy', 'eBay Italy', 'Unieuro', 'MediaWorld'],
    marketChar: 'سوق متطور بمعايير عالية'
  },
  'NL': {
    currency: 'اليورو',
    currencyCode: 'EUR',
    language: 'English',
    platforms: ['Amazon.nl', 'eBay', 'Bol.com', 'Coolblue'],
    topStores: ['Bol.com', 'Coolblue', 'Amazon Netherlands', 'Zalando'],
    marketChar: 'سوق متطور ومنفتح'
  },
  'SE': {
    currency: 'الكرونة السويدية',
    currencyCode: 'SEK',
    language: 'English',
    platforms: ['Amazon.se', 'eBay', 'Webhallen', 'Tradera'],
    topStores: ['Amazon Sweden', 'CDON', 'Webhallen', 'Elgiganten'],
    marketChar: 'سوق متطور مع معايير عالية'
  },
  'CH': {
    currency: 'الفرنك السويسري',
    currencyCode: 'CHF',
    language: 'English',
    platforms: ['Amazon', 'Galaxus', 'Ricardo', 'Migros'],
    topStores: ['Galaxus', 'Digitec', 'Migros', 'Coop'],
    marketChar: 'سوق عالي الجودة والأسعار'
  },
  'AT': {
    currency: 'اليورو',
    currencyCode: 'EUR',
    language: 'English',
    platforms: ['Amazon.at', 'eBay', 'Willhaben', 'Alternate'],
    topStores: ['Amazon Austria', 'Willhaben', 'MediaMarkt', 'Conrad'],
    marketChar: 'سوق متطور في وسط أوروبا'
  },
  'PL': {
    currency: 'الزلوتي البولندي',
    currencyCode: 'PLN',
    language: 'English',
    platforms: ['Amazon.pl', 'Allegro', 'OLX', 'eBay'],
    topStores: ['Allegro', 'Amazon Poland', 'OLX Poland', 'Ceneo'],
    marketChar: 'سوق نام بسرعة في أوروبا الشرقية'
  },
  'NG': {
    currency: 'النيرة النيجيرية',
    currencyCode: 'NGN',
    language: 'English',
    platforms: ['Jumia', 'Konga', 'Jiji', 'OLX'],
    topStores: ['Jumia Nigeria', 'Konga', 'Jiji', 'PayPorte'],
    marketChar: 'سوق نام بسرعة في أفريقيا'
  },
  'ZA': {
    currency: 'الراند الجنوب أفريقي',
    currencyCode: 'ZAR',
    language: 'English',
    platforms: ['Takealot', 'Superbalist', 'Loot', 'Gumtree'],
    topStores: ['Takealot', 'Superbalist', 'Makro', 'Game'],
    marketChar: 'سوق متطور في أفريقيا'
  },
  'KE': {
    currency: 'الشلن الكيني',
    currencyCode: 'KES',
    language: 'English',
    platforms: ['Jumia', 'OLX', 'Kilimall', 'Sokowatch'],
    topStores: ['Jumia Kenya', 'Kilimall', 'Sky.Garden', 'Masoko'],
    marketChar: 'سوق نام مع اقتصاد رقمي قوي'
  },
  'US': {
    currency: 'الدولار الأمريكي',
    currencyCode: 'USD',
    language: 'English',
    platforms: ['Amazon.com', 'eBay', 'Walmart', 'Target'],
    topStores: ['Amazon', 'Walmart', 'eBay', 'Target', 'Best Buy', 'Costco', 'Home Depot'],
    marketChar: 'أكبر سوق إلكترونية في العالم'
  },
  'CA': {
    currency: 'الدولار الكندي',
    currencyCode: 'CAD',
    language: 'English',
    platforms: ['Amazon.ca', 'eBay', 'Shopify', 'Kijiji'],
    topStores: ['Amazon Canada', 'Walmart Canada', 'Best Buy Canada', 'Canadian Tire'],
    marketChar: 'سوق متطور وقوي'
  },
  'MX': {
    currency: 'البيزو المكسيكي',
    currencyCode: 'MXN',
    language: 'Spanish',
    platforms: ['Mercado Libre', 'Amazon.mx', 'OLX', 'Shopify'],
    topStores: ['Mercado Libre', 'Amazon Mexico', 'Liverpool', 'Palacio de Hierro'],
    marketChar: 'سوق متنامي في أمريكا اللاتينية'
  },
  'BR': {
    currency: 'الريال البرازيلي',
    currencyCode: 'BRL',
    language: 'Portuguese',
    platforms: ['Mercado Livre', 'B2Brazil', 'Amazon.br', 'OLX'],
    topStores: ['Mercado Livre', 'Amazon Brazil', 'Magazine Luiza', 'Americanas'],
    marketChar: 'أكبر سوق في أمريكا اللاتينية'
  },
  'AR': {
    currency: 'البيزو الأرجنتيني',
    currencyCode: 'ARS',
    language: 'Spanish',
    platforms: ['Mercado Libre', 'Amazon.ar', 'OLX', 'Tiendamia'],
    topStores: ['Mercado Libre', 'Garbarino', 'Fravega', 'Musimundo'],
    marketChar: 'سوق قوي مع منافسة عالية'
  },
};
